INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(1, '01', 'Pgno.Norte-Glorieta Plus Ultra', 2, '#f54129');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(2, '02', 'Barqueta-Glorieta Heliopolis', 2, '#f54129');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(3, '03', 'Bellavista - Pino Montano', 2, '#f54129');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(5, '05', 'Puerta Triana-Santa Aurelia', 2, '#f54129');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(6, '06', 'San Lazaro-Glorieta Heliopolis', 2, '#f54129');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(10, '10', 'Ponce de Leon -San Jeronimo', 3, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(11, '11', 'Pz.Ponce de Leon-Los Principes', 3, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(12, '12', 'Ponce de  Leon-Pino Montano', 3, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(13, '13', 'Plaza Duque-Pino Montano', 3, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(14, '14', 'Plaza Duque-Poligono Norte', 3, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(15, '15', 'Ponce de Leon-San Diego', 3, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(16, '16', 'Pza.Jeron. Cordoba-Valdezorras', 3, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(20, '20', 'Ponce de Leon-Pgno.San Pablo', 4, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(21, '21', 'Prado-Poligono S. Pablo', 4, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(22, '22', 'Prado-Sevilla Este', 4, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(24, '24', 'Ponce de Leon-Palmete', 4, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(25, '25', 'Prado-Rochelambert', 4, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(26, '26', 'Prado-Cerro del Aguila', 4, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(27, '27', 'Plaza del - Duque-Sevilla Este', 4, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(28, '28', 'Prado-Parque Alcosa', 4, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(29, '29', 'Prado-Torreblanca', 4, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(30, '30', 'Prado-La Paz', 5, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(31, '31', 'Prado-Poligono Sur', 5, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(32, '32', 'Plaza del - Duque-Poligono Sur', 5, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(34, '34', 'Prado-Los Bermejales', 5, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(37, '37', 'Prado - Bellavista', 5, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(38, '38', 'Prado - Univ.Pablo Olavide', 5, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(125, '38A', 'Prado - Pitamo - Upo', 5, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(39, '39', 'Los Arcos-Hacienda San Antonio', 4, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(40, '40', 'Plaza Magdalena-Triana', 6, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(41, '41', 'Plz. Magdalena-Los Remedios', 6, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(43, '43', 'Plaza Magdalena- El Turruñuelo', 6, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(52, '52', 'San Bernardo-Palmete', 4, '#742929');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(53, '53', 'Los Arcos - C.Penitenciario', 4, '#742929');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(101, 'A1', 'Prado- Pino Montano', 9, '#000000');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(102, 'A2', 'Prado - San Jeronimo', 9, '#000000');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(103, 'A3', 'Prado - Sevilla Este', 9, '#000000');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(104, 'A4', 'Prado - Santa Aurelia', 9, '#000000');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(105, 'A5', 'Prado - Poligono Sur', 9, '#000000');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(106, 'A6', 'Prado - Bellavista', 9, '#000000');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(107, 'A7', 'Circular Nocturno', 9, '#000000');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(110, 'A8', 'Prado - Parque Alcosa', 7, '#000000');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(87, 'B3', 'Gran Plaza-Santa Clara', 7, '#84c6e3');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(119, 'B4', 'San Bernardo-Torreblanca', 7, '#84c6e3');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(81, 'C1', 'Isla de La Cartuja-Prado', 1, '#008431');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(82, 'C2', 'Isla de La Cartuja-Prado', 1, '#008431');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(83, 'C3', 'Barqueta-Prado', 1, '#008431');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(84, 'C4', 'Barqueta-Prado', 1, '#008431');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(121, 'C5', 'Plaza Duque-Plaza S. Francisco', 1, '#008431');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(108, 'C6A', 'Circular Macarena Norte', 1, '#008431');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(109, 'C6B', 'Circular Macarena Norte', 1, '#008431');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(100, 'EA', 'Especial -  Aeropuerto', 7, '#84c6e3');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES(60, 'T1', 'Plaza Nueva-San Bernardo', 8, '#c60018');

