INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (1, '01', 'Plg. Norte H. Virgen del Rocio', 1, '#f54129');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (2, '02', 'Barqueta Heliopolis', 1, '#f54129');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (3, '03', 'Bellavista-S. Jeronimo-Pino Montano', 1, '#f54129');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (5, '05', 'Puerta Triana - Santa Aurelia', 1, '#f54129');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (6, '06', 'Gta. S. Lázaro - Hosp. V. Rocio', 1, '#f54129');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (10, '10', 'Ponce de León - San Jerónimo', 1, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (11, '11', 'Ponce de León - Los Principes', 1, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (12, '12', 'Ponce de León -  Pino Montano', 1, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (13, '13', 'Plaza Duque Pino Montano', 1, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (14, '14', 'Plaza Duque - Poligono Norte - Las Golondrinas', 1, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (15, '15', 'Ponce de León - San Diego', 1, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (16, '16', 'Valdezorras - Rialto', 1, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (20, '20', 'Ponce de León - Polígono de San Pablo', 1, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (21, '21', 'Plaza de Armas - Polígono San Pablo', 1, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (22, '22', 'Prado San Sebastian - Sevilla Este', 1, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (24, '24', 'Ponce de León - Juan XXIII - Palmete', 1, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (25, '25', 'Prado - Rochelambert', 1, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (26, '26', 'Prado - Cerro del Aguila', 1, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (27, '27', 'Plaza Duque - Sevilla Este', 1, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (28, '28', 'Prado - Alcosa', 1, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (29, '29', 'Prado S. Sebastian - Torreblanca', 1, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (30, '30', 'Prado San Sebastián - La Paz', 1, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (31, '31', 'Prado San Sebastián - Polígono Sur', 1, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (32, '32', 'Plz. Duque - Plg. Sur', 1, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (34, '34', 'Prado San Sebastián - Los Bermejales', 1, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (37, '37', 'Pta. Jerez - Pedro Salvador - Bellavista', 1, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (38, '38', 'Prado - Univ. P. Olavide', 1, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (125, '38A', 'Prado - Pitamo - Olavide', 1, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (39, '39', 'Los Arcos - Hac. S. Antonio', 1, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (40, '40', 'Plz. Magdalena - Triana', 1, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (41, '41', 'Plz. Magadalena - Tablada', 1, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (43, '43', 'Plz. Magdalena - El Tardon', 1, '#000d6f');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (52, '52', 'S. Bernardo - Palmete', 1, '#742929');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (87, 'B3', 'Gran Plaza - Santa Clara', 1, '#84c6e3');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (119, 'B4', 'San Bernardo - Torreblanca', 1, '#84c6e3');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (81, 'C1', 'Circular Exterior 1', 1, '#008431');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (82, 'C2', 'Circular Exterior 2', 1, '#008431');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (83, 'C3', 'Circular Interior 1', 1, '#008431');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (84, 'C4', 'Circular Interior 2', 1, '#008431');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (121, 'C5', 'Circular Centro 5', 1, '#008431');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (108, 'C6A', 'Circular Macarena Norte Sentido A', 1, '#008431');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (109, 'C6B', 'Circular Macarena Norte Sentido B', 1, '#008431');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (100, 'EA', 'Aeropuerto', 1, '#84c6e3');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (70, 'LC', 'Lanzadera Cartuja', 1, '#f7a800');
INSERT INTO linea (id, numero, nombre, tipo_id, color) VALUES (60, 'T1', 'Metrocentro', 1, '#c60018');
