INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(1, 'CIUDAD SANITARIA', 1, '6:00', '0:06', 1);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(2, 'POLIGONO NORTE', 2, '6:00', '0:06', 1);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(3, 'BARQUETA    ', 2, '5:41', '0:15', 2);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(4, 'HELIOPOLIS   ', 1, '5:41', '0:15', 2);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(5, 'BELLAVISTA', 2, '6:00', '0:37', 3);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(6, 'PINO MONTANO', 1, '6:00', '0:37', 3);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(7, 'PUERTA TRIANA', 2, '5:56', '0:31', 5);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(8, 'SANTA AURELIA', 1, '5:56', '0:31', 5);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(9, 'HELIOPOLIS   ', 1, '6:00', '0:19', 6);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(10, 'SAN LAZARO', 2, '6:00', '0:19', 6);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(11, 'PLAZA PONCE DE LEON', 2, '6:00', '23:59', 10);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(12, 'SAN JERONIMO', 1, '6:00', '23:59', 10);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(13, 'BARRIADA LOS PRINCIPES', 1, '6:00', '23:55', 11);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(14, 'PLAZA PONCE DE LEON', 2, '6:00', '23:55', 11);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(15, 'PINO MONTANO', 1, '6:00', '23:55', 12);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(16, 'PLAZA PONCE DE LEON', 2, '6:00', '23:55', 12);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(17, 'PINO MONTANO', 1, '6:00', '0:01', 13);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(18, 'PLAZA DEL DUQUE', 2, '6:00', '0:01', 13);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(19, 'PLAZA DEL DUQUE', 2, '6:00', '23:53', 14);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(20, 'POLIGONO NORTE', 1, '6:00', '23:53', 14);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(21, 'PLAZA PONCE DE LEON', 2, '6:00', '23:53', 15);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(22, 'SAN DIEGO', 1, '6:00', '23:53', 15);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(23, 'PLAZA PONCE DE LEON', 2, '6:00', '2:30', 16);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(24, 'VALDEZORRAS  ', 1, '6:00', '2:30', 16);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(25, 'PLAZA PONCE DE LEON', 2, '6:00', '23:52', 20);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(26, 'POLIGONO SAN PABLO', 1, '6:00', '23:52', 20);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(27, 'POLIGONO SAN PABLO', 1, '6:00', '23:52', 21);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(28, 'PRADO DE S.SEBASTIAN', 2, '6:00', '23:52', 21);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(29, 'PRADO DE S.SEBASTIAN', 2, '6:00', '0:17', 22);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(30, 'SEVILLA ESTE', 1, '6:00', '0:17', 22);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(31, 'PLAZA PONCE DE LEON', 2, '6:00', '0:04', 24);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(32, 'ROCHELAMBERT N. PALMETE', 1, '6:00', '0:04', 24);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(33, 'PRADO DE S.SEBASTIAN', 2, '6:00', '23:53', 25);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(34, 'ROCHELAMBERT  ', 1, '6:00', '23:53', 25);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(35, 'CERRO DEL AGUILA', 1, '6:00', '23:54', 26);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(36, 'PRADO DE S.SEBASTIAN', 2, '6:00', '23:54', 26);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(37, 'PLAZA DEL DUQUE', 2, '5:41', '0:09', 27);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(38, 'SEVILLA ESTE', 1, '5:41', '0:09', 27);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(39, 'PARQUE ALCOSA', 1, '5:00', '0:08', 28);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(40, 'PRADO DE S.SEBASTIAN', 2, '5:00', '0:08', 28);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(41, 'PRADO DE S.SEBASTIAN', 2, '5:30', '2:37', 29);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(42, 'TORREBLANCA   ', 1, '5:30', '2:37', 29);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(43, 'LAS LETANIAS', 1, '6:00', '23:55', 30);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(44, 'PRADO DE S.SEBASTIAN', 2, '6:00', '23:55', 30);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(45, 'BARRIADA MURILLO', 1, '6:00', '23:57', 31);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(46, 'PRADO DE S.SEBASTIAN', 2, '6:00', '23:57', 31);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(47, 'PLAZA DEL DUQUE', 2, '6:00', '0:13', 32);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(48, 'POLIGONO SUR', 1, '6:00', '0:13', 32);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(49, 'LOS BERMEJALES', 1, '6:00', '0:00', 34);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(50, 'PRADO DE S.SEBASTIAN', 2, '6:00', '0:00', 34);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(51, 'BELLAVISTA   ', 1, '6:00', '23:56', 37);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(52, 'PRADO DE S.SEBASTIAN', 2, '6:00', '23:56', 37);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(53, 'PRADO DE S.SEBASTIAN', 2, '0:00', '0:00', 38);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(54, 'UNIV. P.OLAVIDE', 1, '0:00', '0:00', 38);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(55, 'PITAMO U.P.O.', 1, '6:00', '23:55', 125);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(56, 'PRADO DE S.SEBASTIAN', 2, '6:00', '23:55', 125);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(57, 'HACIENDA SAN ANTONIO', 1, '7:00', '23:30', 39);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(58, 'LOS ARCOS', 2, '7:00', '23:30', 39);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(59, 'BARRIADA EL TARDON', 1, '6:00', '23:54', 40);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(60, 'PLAZA MAGDALENA', 2, '6:00', '23:54', 40);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(61, 'PLAZA DE LA MAGDALENA', 2, '6:00', '23:50', 41);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(62, 'TABLADA    ', 1, '6:00', '23:50', 41);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(63, 'PLAZA MAGDALENA', 2, '6:00', '23:44', 43);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(64, 'TRIANA     ', 1, '6:00', '23:44', 43);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(65, 'BARRIADA PALMETE', 1, '6:00', '23:56', 52);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(66, 'SAN BERNARDO', 2, '6:00', '23:56', 52);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(67, 'CENTRO PENITENCIARIO', 1, '7:30', '20:40', 53);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(68, 'LOS ARCOS', 2, '7:30', '20:40', 53);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(69, 'PINO MONTANO', 1, '23:51', '3:00', 101);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(70, 'PRADO DE S.SEBASTIAN', 2, '23:51', '3:00', 101);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(71, 'PRADO DE S.SEBASTIAN', 2, '23:56', '3:00', 102);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(72, 'SAN JERONIMO', 1, '23:56', '3:00', 102);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(73, 'PRADO DE S.SEBASTIAN', 2, '0:00', '3:00', 103);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(74, 'SEVILLA ESTE', 1, '0:00', '3:00', 103);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(75, 'PRADO DE S.SEBASTIAN', 2, '23:44', '3:00', 104);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(76, 'SANTA AURELIA', 1, '23:44', '3:00', 104);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(77, 'POLIGONO SUR', 1, '23:43', '3:00', 105);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(78, 'PRADO DE S.SEBASTIAN', 2, '23:43', '3:00', 105);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(79, 'BELLAVISTA   ', 1, '23:53', '3:00', 106);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(80, 'PRADO DE S.SEBASTIAN', 2, '23:53', '3:00', 106);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(81, 'PRADO SAN SEBASTIAN', 2, '0:00', '3:00', 107);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(82, 'TORNEO  ', 1, '0:00', '3:00', 107);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(83, 'PARQUE ALCOSA', 1, '23:56', '3:00', 110);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(84, 'PRADO DE S.SEBASTIAN', 2, '23:56', '3:00', 110);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(85, 'NERVION    ', 2, '6:00', '23:43', 87);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(86, 'SANTA CLARA', 1, '6:00', '23:43', 87);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(87, 'SAN BERNARDO ', 2, '6:00', '0:13', 119);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(88, 'TORREBLANCA   ', 1, '6:00', '0:13', 119);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(89, 'CIRCULAR', 99, '6:00', '0:16', 81);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(90, 'CIRCULAR', 99, '5:53', '23:58', 82);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(91, 'CIRCULAR', 99, '6:00', '23:45', 83);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(92, 'CIRCULAR', 99, '6:00', '23:48', 84);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(93, 'CIRCULAR', 99, '9:52', '21:51', 121);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(94, 'CIRCULAR', 99, '7:10', '0:20', 108);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(95, 'CIRCULAR', 99, '0:00', '0:00', 109);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(96, 'AEROPUERTO', 1, '4:24', '2:00', 100);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(97, 'PLAZA DE ARMAS', 2, '4:24', '2:00', 100);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(98, 'PLAZA NUEVA', 2, '6:00', '1:53', 60);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(99, 'SAN BERNARDO', 1, '6:00', '1:53', 60);

