INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(694, 'HOSPITAL V.ROCIO', 1, '6:00', '0:06', 1);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(695, 'POLIGONO NORTE', 2, '6:00', '0:06', 1);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(696, 'BARQUETA    ', 2, '5:43', '0:11', 2);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(697, 'HELIOPOLIS   ', 1, '5:43', '0:11', 2);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(698, 'BELLAVISTA', 2, '5:58', '0:46', 3);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(699, 'PINO MONTANO', 1, '5:58', '0:46', 3);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(700, 'PUERTA TRIANA', 2, '5:56', '0:32', 5);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(701, 'SANTA AURELIA', 1, '5:56', '0:32', 5);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(702, 'HELIOPOLIS   ', 1, '6:00', '0:17', 6);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(703, 'SAN LAZARO', 2, '6:00', '0:17', 6);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(704, 'PLAZA PONCE DE LEON', 2, '6:00', '23:54', 10);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(705, 'SAN JERONIMO', 1, '6:00', '23:54', 10);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(706, 'BARRIADA LOS PRINCIPES', 1, '6:00', '23:55', 11);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(707, 'PLAZA PONCE DE LEON', 2, '6:00', '23:55', 11);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(708, 'PINO MONTANO', 1, '6:00', '0:05', 12);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(709, 'PLAZA PONCE DE LEON', 2, '6:00', '0:05', 12);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(710, 'PINO MONTANO', 1, '6:00', '0:07', 13);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(711, 'PLAZA DEL DUQUE', 2, '6:00', '0:07', 13);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(712, 'PLAZA DEL DUQUE', 2, '6:00', '23:49', 14);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(713, 'POLIGONO NORTE', 1, '6:00', '23:49', 14);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(714, 'PLAZA PONCE DE LEON', 2, '6:00', '23:51', 15);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(715, 'SAN DIEGO', 1, '6:00', '23:51', 15);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(716, 'PLAZA PONCE DE LEON', 2, '6:00', '0:00', 16);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(717, 'VALDEZORRAS  ', 1, '6:00', '0:00', 16);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(718, 'PLAZA PONCE DE LEON', 2, '6:00', '23:48', 20);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(719, 'POLIGONO SAN PABLO', 1, '6:00', '23:48', 20);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(720, 'PLAZA DE ARMAS', 2, '6:00', '0:02', 21);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(721, 'POLIGONO SAN PABLO', 1, '6:00', '0:02', 21);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(722, 'PRADO DE S.SEBASTIAN', 2, '6:00', '0:05', 22);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(723, 'SEVILLA ESTE', 1, '6:00', '0:05', 22);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(724, 'PLAZA PONCE DE LEON', 2, '6:00', '0:05', 24);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(725, 'ROCHELAMBERT N. PALMETE', 1, '6:00', '0:05', 24);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(726, 'PRADO DE S.SEBASTIAN', 2, '6:00', '23:57', 25);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(727, 'ROCHELAMBERT  ', 1, '6:00', '23:57', 25);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(728, 'CERRO DEL AGUILA', 1, '6:00', '23:56', 26);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(729, 'PRADO DE S.SEBASTIAN', 2, '6:00', '23:56', 26);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(730, 'PLAZA DEL DUQUE', 2, '5:52', '0:09', 27);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(731, 'SEVILLA ESTE', 1, '5:52', '0:09', 27);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(732, 'PARQUE ALCOSA', 1, '5:00', '0:09', 28);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(733, 'PRADO DE S.SEBASTIAN', 2, '5:00', '0:09', 28);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(734, 'PRADO DE S.SEBASTIAN', 2, '5:30', '2:30', 29);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(735, 'TORREBLANCA   ', 1, '5:30', '2:30', 29);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(736, 'LAS LETANIAS', 1, '6:00', '23:54', 30);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(737, 'PRADO DE S.SEBASTIAN', 2, '6:00', '23:54', 30);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(738, 'BARRIADA MURILLO', 1, '6:00', '23:57', 31);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(739, 'PRADO DE S.SEBASTIAN', 2, '6:00', '23:57', 31);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(740, 'PLAZA DEL DUQUE', 2, '6:00', '0:15', 32);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(741, 'POLIGONO SUR', 1, '6:00', '0:15', 32);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(742, 'LOS BERMEJALES', 1, '6:00', '0:05', 34);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(743, 'PRADO DE S.SEBASTIAN', 2, '6:00', '0:05', 34);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(744, 'BELLAVISTA   ', 1, '6:00', '0:08', 37);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(745, 'PUERTA JEREZ', 2, '6:00', '0:08', 37);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(746, 'PRADO DE S.SEBASTIAN', 2, '7:05', '22:55', 38);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(747, 'UNIV. P.OLAVIDE', 1, '7:05', '22:55', 38);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(748, 'PITAMO U.P.O.', 1, '6:00', '0:00', 125);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(749, 'PRADO DE S.SEBASTIAN', 2, '6:00', '0:00', 125);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(750, 'HACIENDA SAN ANTONIO', 1, '7:00', '23:30', 39);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(751, 'LOS ARCOS', 2, '7:00', '23:30', 39);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(752, 'BARRIADA EL TARDON', 1, '6:00', '23:52', 40);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(753, 'PLAZA MAGDALENA', 2, '6:00', '23:52', 40);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(754, 'PLAZA DE LA MAGDALENA', 2, '6:00', '23:59', 41);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(755, 'TABLADA    ', 1, '6:00', '23:59', 41);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(756, 'PLAZA MAGDALENA', 2, '6:00', '23:50', 43);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(757, 'TRIANA     ', 1, '6:00', '23:50', 43);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(758, 'BARRIADA PALMETE', 1, '6:00', '0:01', 52);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(759, 'SAN BERNARDO', 2, '6:00', '0:01', 52);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(760, 'CENTRO PENITENCIARIO', 1, '0:00', '0:00', 53);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(761, 'LOS ARCOS', 2, '0:00', '0:00', 53);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(762, 'PINO MONTANO', 1, '0:00', '3:00', 101);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(763, 'PRADO DE S.SEBASTIAN', 2, '0:00', '3:00', 101);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(764, 'PRADO DE S.SEBASTIAN', 2, '0:00', '3:00', 102);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(765, 'SAN JERONIMO', 1, '0:00', '3:00', 102);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(766, 'PRADO DE S.SEBASTIAN', 2, '0:00', '3:00', 103);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(767, 'SEVILLA ESTE', 1, '0:00', '3:00', 103);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(768, 'PRADO DE S.SEBASTIAN', 2, '0:00', '3:00', 104);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(769, 'SANTA AURELIA', 1, '0:00', '3:00', 104);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(770, 'POLIGONO SUR', 1, '0:00', '3:00', 105);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(771, 'PRADO DE S.SEBASTIAN', 2, '0:00', '3:00', 105);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(772, 'BELLAVISTA   ', 1, '0:00', '3:00', 106);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(773, 'PRADO DE S.SEBASTIAN', 2, '0:00', '3:00', 106);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(774, 'PRADO SAN SEBASTIAN', 2, '0:00', '3:00', 107);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(775, 'TORNEO  ', 1, '0:00', '3:00', 107);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(776, 'PARQUE ALCOSA', 1, '0:00', '3:00', 110);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(777, 'PRADO DE S.SEBASTIAN', 2, '0:00', '3:00', 110);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(778, 'NERVION    ', 2, '6:00', '23:41', 87);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(779, 'SANTA CLARA', 1, '6:00', '23:41', 87);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(780, 'SAN BERNARDO ', 2, '6:00', '0:23', 119);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(781, 'TORREBLANCA   ', 1, '6:00', '0:23', 119);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(782, 'CIRCULAR', 99, '6:00', '0:06', 81);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(783, 'CIRCULAR', 99, '5:46', '0:03', 82);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(784, 'CIRCULAR', 99, '6:00', '23:48', 83);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(785, 'CIRCULAR', 99, '6:00', '23:53', 84);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(786, 'CIRCULAR', 99, '9:50', '21:49', 121);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(787, 'CIRCULAR', 99, '5:55', '0:20', 108);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(788, 'CIRCULAR', 99, '6:50', '15:30', 109);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(789, 'AEROPUERTO', 1, '4:30', '1:25', 100);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(790, 'PLAZA DE ARMAS', 2, '4:30', '1:25', 100);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(791, 'PLAZA NUEVA', 2, '6:00', '23:47', 60);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(792, 'SAN BERNARDO', 1, '6:00', '23:47', 60);

