INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(397, 'HOSPITAL V.ROCIO', 1, '6:00', '0:12', 1);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(398, 'POLIGONO NORTE', 2, '6:00', '0:12', 1);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(399, 'BARQUETA    ', 2, '5:41', '0:13', 2);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(400, 'HELIOPOLIS   ', 1, '5:41', '0:13', 2);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(401, 'BELLAVISTA', 2, '6:00', '0:35', 3);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(402, 'PINO MONTANO', 1, '6:00', '0:35', 3);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(403, 'PUERTA TRIANA', 2, '5:56', '0:54', 5);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(404, 'SANTA AURELIA', 1, '5:56', '0:54', 5);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(405, 'HELIOPOLIS   ', 1, '6:00', '0:24', 6);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(406, 'SAN LAZARO', 2, '6:00', '0:24', 6);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(407, 'PLAZA PONCE DE LEON', 2, '6:00', '23:58', 10);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(408, 'SAN JERONIMO', 1, '6:00', '23:58', 10);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(409, 'BARRIADA LOS PRINCIPES', 1, '6:00', '23:53', 11);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(410, 'PLAZA PONCE DE LEON', 2, '6:00', '23:53', 11);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(411, 'PINO MONTANO', 1, '6:00', '0:01', 12);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(412, 'PLAZA PONCE DE LEON', 2, '6:00', '0:01', 12);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(413, 'PINO MONTANO', 1, '6:00', '0:06', 13);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(414, 'PLAZA DEL DUQUE', 2, '6:00', '0:06', 13);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(415, 'PLAZA DEL DUQUE', 2, '6:00', '23:59', 14);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(416, 'POLIGONO NORTE', 1, '6:00', '23:59', 14);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(417, 'PLAZA PONCE DE LEON', 2, '6:00', '23:55', 15);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(418, 'SAN DIEGO', 1, '6:00', '23:55', 15);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(419, 'PLAZA PONCE DE LEON', 2, '6:00', '5:30', 16);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(420, 'VALDEZORRAS  ', 1, '6:00', '5:30', 16);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(421, 'PLAZA PONCE DE LEON', 2, '6:00', '23:57', 20);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(422, 'POLIGONO SAN PABLO', 1, '6:00', '23:57', 20);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(423, 'PLAZA DE ARMAS', 2, '6:00', '0:04', 21);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(424, 'POLIGONO SAN PABLO', 1, '6:00', '0:04', 21);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(425, 'PRADO DE S.SEBASTIAN', 2, '6:00', '0:10', 22);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(426, 'SEVILLA ESTE', 1, '6:00', '0:10', 22);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(427, 'PLAZA PONCE DE LEON', 2, '6:00', '0:01', 24);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(428, 'ROCHELAMBERT N. PALMETE', 1, '6:00', '0:01', 24);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(429, 'PRADO DE S.SEBASTIAN', 2, '6:00', '23:52', 25);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(430, 'ROCHELAMBERT  ', 1, '6:00', '23:52', 25);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(431, 'CERRO DEL AGUILA', 1, '6:00', '23:55', 26);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(432, 'PRADO DE S.SEBASTIAN', 2, '6:00', '23:55', 26);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(433, 'PLAZA DEL DUQUE', 2, '5:41', '0:15', 27);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(434, 'SEVILLA ESTE', 1, '5:41', '0:15', 27);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(435, 'PARQUE ALCOSA', 1, '5:00', '0:08', 28);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(436, 'PRADO DE S.SEBASTIAN', 2, '5:00', '0:08', 28);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(437, 'PRADO DE S.SEBASTIAN', 2, '5:23', '6:05', 29);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(438, 'TORREBLANCA   ', 1, '5:23', '6:05', 29);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(439, 'LAS LETANIAS', 1, '6:00', '23:56', 30);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(440, 'PRADO DE S.SEBASTIAN', 2, '6:00', '23:56', 30);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(441, 'BARRIADA MURILLO', 1, '6:00', '23:52', 31);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(442, 'PRADO DE S.SEBASTIAN', 2, '6:00', '23:52', 31);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(443, 'PLAZA DEL DUQUE', 2, '6:00', '0:08', 32);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(444, 'POLIGONO SUR', 1, '6:00', '0:08', 32);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(445, 'LOS BERMEJALES', 1, '6:00', '0:05', 34);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(446, 'PRADO DE S.SEBASTIAN', 2, '6:00', '0:05', 34);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(447, 'BELLAVISTA   ', 1, '6:04', '0:10', 37);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(448, 'PUERTA JEREZ', 2, '6:04', '0:10', 37);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(449, 'PRADO DE S.SEBASTIAN', 2, '0:00', '0:00', 38);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(450, 'UNIV. P.OLAVIDE', 1, '0:00', '0:00', 38);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(451, 'PITAMO U.P.O.', 1, '6:00', '23:55', 125);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(452, 'PRADO DE S.SEBASTIAN', 2, '6:00', '23:55', 125);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(453, 'HACIENDA SAN ANTONIO', 1, '7:00', '23:30', 39);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(454, 'LOS ARCOS', 2, '7:00', '23:30', 39);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(455, 'BARRIADA EL TARDON', 1, '6:00', '23:45', 40);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(456, 'PLAZA MAGDALENA', 2, '6:00', '23:45', 40);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(457, 'PLAZA DE LA MAGDALENA', 2, '6:00', '0:17', 41);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(458, 'TABLADA    ', 1, '6:00', '0:17', 41);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(459, 'EL TARDON   ', 1, '6:00', '23:52', 43);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(460, 'PLAZA MAGDALENA', 2, '6:00', '23:52', 43);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(461, 'BARRIADA PALMETE', 1, '6:00', '0:14', 52);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(462, 'SAN BERNARDO', 2, '6:00', '0:14', 52);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(463, 'CENTRO PENITENCIARIO', 1, '7:30', '20:40', 53);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(464, 'LOS ARCOS', 2, '7:30', '20:40', 53);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(465, 'PINO MONTANO', 1, '0:00', '6:00', 101);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(466, 'PRADO DE S.SEBASTIAN', 2, '0:00', '6:00', 101);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(467, 'PRADO DE S.SEBASTIAN', 2, '23:56', '6:00', 102);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(468, 'SAN JERONIMO', 1, '23:56', '6:00', 102);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(469, 'PRADO DE S.SEBASTIAN', 2, '23:52', '6:00', 103);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(470, 'SEVILLA ESTE', 1, '23:52', '6:00', 103);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(471, 'PRADO DE S.SEBASTIAN', 2, '23:44', '6:00', 104);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(472, 'SANTA AURELIA', 1, '23:44', '6:00', 104);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(473, 'POLIGONO SUR', 1, '23:43', '6:00', 105);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(474, 'PRADO DE S.SEBASTIAN', 2, '23:43', '6:00', 105);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(475, 'BELLAVISTA   ', 1, '23:53', '6:00', 106);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(476, 'PRADO DE S.SEBASTIAN', 2, '23:53', '6:00', 106);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(477, 'PRADO SAN SEBASTIAN', 2, '23:56', '6:00', 107);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(478, 'TORNEO  ', 1, '23:56', '6:00', 107);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(479, 'PARQUE ALCOSA', 1, '23:57', '6:00', 110);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(480, 'PRADO DE S.SEBASTIAN', 2, '23:57', '6:00', 110);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(481, 'NERVION    ', 2, '6:00', '23:42', 87);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(482, 'SANTA CLARA', 1, '6:00', '23:42', 87);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(483, 'SAN BERNARDO ', 2, '6:00', '0:20', 119);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(484, 'TORREBLANCA   ', 1, '6:00', '0:20', 119);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(485, 'CIRCULAR', 99, '6:00', '0:28', 81);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(486, 'CIRCULAR', 99, '5:53', '0:01', 82);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(487, 'CIRCULAR', 99, '6:00', '23:53', 83);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(488, 'CIRCULAR', 99, '6:00', '23:50', 84);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(489, 'CIRCULAR', 99, '9:50', '21:49', 121);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(490, 'CIRCULAR', 99, '7:10', '0:20', 108);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(491, 'CIRCULAR', 99, '0:00', '0:00', 109);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(492, 'AEROPUERTO', 1, '4:30', '1:25', 100);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(493, 'PLAZA DE ARMAS', 2, '4:30', '1:25', 100);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(494, 'PLAZA NUEVA', 2, '6:00', '2:10', 60);
INSERT INTO seccion (id, nombreSeccion, numeroSeccion, horaInicio, horaFin, linea_id) VALUES(495, 'SAN BERNARDO', 1, '6:00', '2:10', 60);

